import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Rectangle260(),
        ]),
      ),
    );
  }
}

class Rectangle260 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 581,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.only(
                topLeft: Radius.circular(32),
                topRight: Radius.circular(32),
              ),
            ),
          ),
        ),
        Transform(
          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-2.36),
          child: Container(
            width: 22.75,
            height: 22.76,
            child: Stack(children: [
                ,
                ]),
          ),
        ),
        Text(
          'Settings',
          style: TextStyle(
            color: Colors.black,
            fontSize: 20,
            fontFamily: 'Gilroy',
            fontWeight: FontWeight.w500,
            height: 0,
          ),
        ),
        Text(
          'Logout',
          style: TextStyle(
            color: Colors.black,
            fontSize: 20,
            fontFamily: 'Gilroy',
            fontWeight: FontWeight.w500,
            height: 0,
          ),
        ),
        Text(
          'Meal Tickets',
          style: TextStyle(
            color: Colors.black,
            fontSize: 20,
            fontFamily: 'Gilroy',
            fontWeight: FontWeight.w500,
            height: 0,
          ),
        ),
        Container(
          width: 246,
          height: 62,
          decoration: ShapeDecoration(
            color: Color(0xFFF0BD2D),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(32),
            ),
          ),
        ),
        Text(
          'Take Attendance',
          style: TextStyle(
            color: Color(0xFF003B65),
            fontSize: 20,
            fontFamily: 'Gilroy',
            fontWeight: FontWeight.w500,
            height: 0,
          ),
        ),
      ],
    );
  }
}